# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/polar/retrogym

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/polar/retrogym

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/polar/retrogym/CMakeFiles /home/polar/retrogym//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/polar/retrogym/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grpc_emulator

# Build rule for target.
grpc_emulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpc_emulator
.PHONY : grpc_emulator

# fast build rule for target.
grpc_emulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/build
.PHONY : grpc_emulator/fast

grpc_emulator.grpc.pb.o: grpc_emulator.grpc.pb.cc.o
.PHONY : grpc_emulator.grpc.pb.o

# target to build an object file
grpc_emulator.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/grpc_emulator.grpc.pb.cc.o
.PHONY : grpc_emulator.grpc.pb.cc.o

grpc_emulator.grpc.pb.i: grpc_emulator.grpc.pb.cc.i
.PHONY : grpc_emulator.grpc.pb.i

# target to preprocess a source file
grpc_emulator.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/grpc_emulator.grpc.pb.cc.i
.PHONY : grpc_emulator.grpc.pb.cc.i

grpc_emulator.grpc.pb.s: grpc_emulator.grpc.pb.cc.s
.PHONY : grpc_emulator.grpc.pb.s

# target to generate assembly for a file
grpc_emulator.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/grpc_emulator.grpc.pb.cc.s
.PHONY : grpc_emulator.grpc.pb.cc.s

grpc_emulator.pb.o: grpc_emulator.pb.cc.o
.PHONY : grpc_emulator.pb.o

# target to build an object file
grpc_emulator.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/grpc_emulator.pb.cc.o
.PHONY : grpc_emulator.pb.cc.o

grpc_emulator.pb.i: grpc_emulator.pb.cc.i
.PHONY : grpc_emulator.pb.i

# target to preprocess a source file
grpc_emulator.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/grpc_emulator.pb.cc.i
.PHONY : grpc_emulator.pb.cc.i

grpc_emulator.pb.s: grpc_emulator.pb.cc.s
.PHONY : grpc_emulator.pb.s

# target to generate assembly for a file
grpc_emulator.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/grpc_emulator.pb.cc.s
.PHONY : grpc_emulator.pb.cc.s

libretro/grpc_emulator.o: libretro/grpc_emulator.cpp.o
.PHONY : libretro/grpc_emulator.o

# target to build an object file
libretro/grpc_emulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/libretro/grpc_emulator.cpp.o
.PHONY : libretro/grpc_emulator.cpp.o

libretro/grpc_emulator.i: libretro/grpc_emulator.cpp.i
.PHONY : libretro/grpc_emulator.i

# target to preprocess a source file
libretro/grpc_emulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/libretro/grpc_emulator.cpp.i
.PHONY : libretro/grpc_emulator.cpp.i

libretro/grpc_emulator.s: libretro/grpc_emulator.cpp.s
.PHONY : libretro/grpc_emulator.s

# target to generate assembly for a file
libretro/grpc_emulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/grpc_emulator.dir/build.make CMakeFiles/grpc_emulator.dir/libretro/grpc_emulator.cpp.s
.PHONY : libretro/grpc_emulator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... grpc_emulator"
	@echo "... grpc_emulator.grpc.pb.o"
	@echo "... grpc_emulator.grpc.pb.i"
	@echo "... grpc_emulator.grpc.pb.s"
	@echo "... grpc_emulator.pb.o"
	@echo "... grpc_emulator.pb.i"
	@echo "... grpc_emulator.pb.s"
	@echo "... libretro/grpc_emulator.o"
	@echo "... libretro/grpc_emulator.i"
	@echo "... libretro/grpc_emulator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

